

stages:
  - build

.build_npm:
  stage: build
  image: node:16.13.0
  script:
    - echo "${WASM_BUILD_JOB_ID}"

.use_artifact:
  stage: build
  script: 
    - ls -l /
    - ls -l peregrine-ensembl/pkg/
  needs:
    - job: Build-WASM
      artifacts: true
      project: ensembl-web/ensembl-dauphin-style-compiler
      ref: multi-project-build

Build:NPM:
  extends: .use_artifact

