stages:
  - build
  - publish
  - update_package
  - update_client

.build_npm:
  stage: build
  image: node:16.13.0
  script: 
    - cp peregrine-ensembl/pkg/* src/peregrine/
    - npm ci --loglevel warn
    - npm run build

  needs:
    - job: Build-WASM
      artifacts: true
      project: ensembl-web/ensembl-dauphin-style-compiler
      ref: multi-project-build

  artifacts:
    paths:
      - dist/

  rules:
    - changes:
      - dist/
      when: never
    - when: always

Build:NPM:
  extends: .build_npm

Publish:
  stage: publish
  image: dockerhub.ebi.ac.uk/ensembl-web/deploy-tools:0.6
  before_script:
    - echo "https://${GIT_USER}:${GIT_TOKEN}@github.com/Ensembl/ensembl-genome-browser.git" >> ~/.git-credentials
  script:
    - git clone https://github.com/Ensembl/ensembl-genome-browser.git
    - cp dist/* ensembl-genome-browser/dist/
    - git -C ensembl-genome-browser add dist/*
    # This needs authentication. Need to create team account (deploy keys)
    - git -C ensembl-genome-browser -c user.name ${GIT_USER} commit -m "Update genome-browser package"
    - git -C ensembl-genome-browser push origin multi-project-pipeline
  rules:
    - changes:
      - dist/
      when: never
    - when: always

Update:NPM:
  stage: update_package
  script:
    - echo "Update Package.json"
  rules:
    - changes:
      - dist/
      when: never
    - when: always

Update:Client:
  stage: update_client
  script:
    - echo "Trigger Ensembl Client"
  rules:
    - changes:
      - dist/
      when: never
    - when: always
