

stages:
  - build

.build_npm:
  stage: build
  image: node:16.13.0
  script:
    - echo "${WASM_BUILD_JOB_ID}"

.use_artifact:
  stage: build
  script: 
    - ls -l /
    - ls -l pkg/
  needs:
    - project: ensembl-dauphin-style-compiler
      job: Build-WASM
      ref: multi-project-build
      artifacts: true

Build:NPM:
  extends: .use_artifact

