stages:
  - build
  - update_client

.build_npm:
  stage: build
  image: node:16.13.0
  script: 
    - cp peregrine-ensembl/pkg/* src/peregrine/
    - npm ci --loglevel warn
    - npm run build
    - cd ..
    - tar -zcf ensemb-genome-browser-npm.tar.gz ensemb-genome-browser

  needs:
    - job: Build-WASM
      artifacts: true
      project: ensembl-web/ensembl-dauphin-style-compiler
      ref: multi-project-build

  artifacts:
    paths:
      - ensemb-genome-browser-npm.tar.gz

  rules:
    - if: '$CI_DEPLOY_FREEZE == null && $CI_COMMIT_BRANCH == "multi-project-build"'
      changes:
      - dist/
      when: never
    - when: always

Build:NPM:
  extends: .build_npm

Update:npm:
  stage: update_client
  variables:
    UPSTREAM_BRANCH: $CI_COMMIT_REF_NAME
    WASM_BUILD_JOB_ID: ${BUILD_JOB_ID}

  trigger:
    project: ensembl-web/ensembl-client
    branch: multi-project-pipeline

  rules:
    - if: '$CI_DEPLOY_FREEZE == null && $CI_COMMIT_BRANCH == "multi-project-build"'
      changes:
        - dist/
      when: never
    - when: always