

stages:
  - build

.build_npm:
  stage: build
  image: node:16.13.0
  script:
    - echo "${WASM_BUILD_JOB_ID}"

.use_artifact:
  script: 
    - ls -l /
    - ls -l pkg/
  needs:
    - pipeline: $WASM_BUILD_JOB_ID
      job: Build-WASM

Build:NPM:
  extends: .use-artifact

