stages:
  - build
  - update_client

.build_npm:
  stage: build
  image: node:16.13.0
  script: 
    - cp peregrine-ensembl/pkg/* src/peregrine/
    - npm ci --loglevel warn
    - npm run build
    - cd ..
    - tar -zcf ensembl-genome-browser-npm.tar.gz ensembl-genome-browser
    - cp ensembl-genome-browser-npm.tar.gz ensembl-genome-browser/

  needs:
    - job: Build-WASM
      artifacts: true
      project: ensembl-web/ensembl-dauphin-style-compiler
      ref: $DSC_UPSTREAM_BRANCH

  artifacts:
    paths:
      - ensembl-genome-browser-npm.tar.gz

Build:NPM:
  extends: .build_npm

Update:npm:
  stage: update_client
  variables:
    GB_UPSTREAM_BRANCH: $CI_COMMIT_REF_NAME
    WASM_BUILD_JOB_ID: ${BUILD_JOB_ID}

  trigger:
    project: ensembl-web/ensembl-client
    branch: $DSC_UPSTREAM_BRANCH
