

stages:
  - build

.build_npm:
  stage: build
  script: 
    - cp peregrine-ensembl/pkg/* src/peregrine/
    - ls -l .
    - npm ci --loglevel warn
    - npm run build
    - ls -l dist/

  needs:
    - job: Build-WASM
      artifacts: true
      project: ensembl-web/ensembl-dauphin-style-compiler
      ref: multi-project-build

Build:NPM:
  extends: .build_npm

